### PR TITLE
Viewer that accepts query params for iframe url use

### PR DESCRIPTION
**Pull request by jrlarano**
Relates to: https://github.com/tjek/octopus/issues/337

### CODE REVIEW

**Review by mortenbo — COMMENTED** [review]
Cool! 1) Maybe embed custom.js into the HTML itself? 2) "viewer/index.html" is too vague. Maybe `embeds/publication-viewer.html`?

**Review by mortenbo — APPROVED** [review]
Maybe add <meta name="robots" content="noindex"> too. Otherwise nice.

**Comment by jrlarano** [comment]
> Maybe add too. Otherwise nice.

@mortenbo Looks like you forgot to type the thing you want me to add? 😄

**Comment by mortenbo** [comment]
@jrlarano Lol, weird. I tried to write you could add `<meta name="robots" content="noindex">`

**Comment by jrlarano** [comment]
I see, that's weird 😄 Done adding the `<meta name="robots" content="noindex">`. Will merge this now 🙂

**Pull request merged**
