### PR TITLE
Jl/sidebar enhancement

### PR DESCRIPTION
**Pull request by jrlarano**
Incito sidebar improvements:
- Hover and Active highlight effect
- Reflect sectionid in hash/query param
- Support section deeplink

### CODE REVIEW

**Review by klarstrup — APPROVED** [review]

**Review by klarstrup — APPROVED** [review]

**Comment by jrlarano** [comment]
@mortenbo waiting for your feedback/approval as well 🙂

**Comment by mortenbo** [comment]
@jrlarano Don't wait on me - or just poke me on Slack 👍

@klarstrup One question though: Can't we consolidate some of this logic in relation to section tracking?

**Comment by klarstrup** [comment]
@mortenbo Sorry, I don't follow. I don't see anything about event tracking in this PR?

@jrlarano Merge at your leisure

**Comment by mortenbo** [comment]
@klarstrup Not what I meant. I meant this PR has hooks for when a section scrolls into view, which is the exact same logic as the event tracking for sections. Why not have "global" hooks you can listen in on, for this purpose here too?

**Comment by klarstrup** [comment]
> @klarstrup Not what I meant. I meant this PR has hooks for when a section scrolls into view, which is the exact same logic as the event tracking for sections. Why not have "global" hooks you can listen in on, for this purpose here too?

Oh those events aren't useful for this at all, they can't tell you which section is the most visible one and they won't fire reliably for that as two sections can be visible simultaneously, scrolling can happen and which one is the most visible one will change without the event firing again as no section has truly appeared/disappeared

**Comment by mortenbo** [comment]
OK 👍

**Pull request merged**
