### PR TITLE
Sanity check URLs and fix fonts. Not sure how it worked before

### PR DESCRIPTION
**Pull request by mortenbo**

### CODE REVIEW

**Review by klarstrup — APPROVED** [review]

**Comment by mortenbo** [comment]
@klarstrup Can you shed some light on what running version of Incito the JS SDK is using? Because from my point of view, fonts could never have worked due to the missing `let i = 0` in the for loops. Maybe it's a newly introduced bug that hasn't gotten out yet.

**Comment by klarstrup** [comment]
> @klarstrup Can you shed some light on what running version of Incito the JS SDK is using? Because from my point of view, fonts could never have worked due to the missing `let i = 0` in the for loops. Maybe it's a newly introduced bug that hasn't gotten out yet.

Yeah sorry this is a bug i introduced in https://github.com/shopgun/shopgun-js-sdk/commit/3ef6e9ee70dbf1e5ad55a302063f2b13ecf821cb trying to get the bundle size down, I must've not noticed fonts breaking while testing this

**Review by simonmarqvard — APPROVED** [review]
Looks good to me!

**Review by jrlarano — APPROVED** [review]

**Comment by mortenbo** [comment]
> Yeah sorry this is a bug i introduced in [3ef6e9e](https://github.com/shopgun/shopgun-js-sdk/commit/3ef6e9ee70dbf1e5ad55a302063f2b13ecf821cb) trying to get the bundle size down, I must've not noticed fonts breaking while testing this

No worries. I assume it's not out in prod as we'd seen the issue then?

**Comment by klarstrup** [comment]
> > Yeah sorry this is a bug i introduced in [3ef6e9e](https://github.com/shopgun/shopgun-js-sdk/commit/3ef6e9ee70dbf1e5ad55a302063f2b13ecf821cb) trying to get the bundle size down, I must've not noticed fonts breaking while testing this
> 
> No worries. I assume it's not out in prod as we'd seen the issue then?

yeah last release was from this commit i believe https://github.com/shopgun/shopgun-js-sdk/commit/bb8d1c9231ee76f925cc1a5e8d4cc866ffb6a2eb

**Pull request merged**
