### PR TITLE
Fix query params - remove on close

### PR DESCRIPTION
**Pull request by jrlarano**

### CODE REVIEW

**Review by klarstrup — APPROVED** [review]

**Comment by jrlarano** [comment]
@klarstrup can we deploy this today? One of our clients is waiting for the fix 🙂

**Comment by klarstrup** [comment]
oh sure

**Comment by klarstrup** [comment]
4.17.2 is out

**Comment by jrlarano** [comment]
@klarstrup Thank you! 🚀

**Pull request merged**
