### PR TITLE
Jl/multipack

### PR DESCRIPTION
**Pull request by jrlarano**
Relates to: https://github.com/tjek/octopus/issues/374#issuecomment-2376372443

This will display the original price and the discounted price of a multipack offer based on the quantity. 
image

### CODE REVIEW

**Review by klarstrup — APPROVED** [review]

**Comment by jrlarano** [comment]
Hi @klarstrup, can we release this today or this week?

**Comment by klarstrup** [comment]
We can, is right now okay?

**Comment by jrlarano** [comment]
Hi @klarstrup yes, we can release this now 🙂

**Comment by klarstrup** [comment]
With respect to your office hours I'll release it when I come online tomorrow morning :]

**Comment by jrlarano** [comment]
@klarstrup Thank you! Let me know once you released it today 🙂

**Comment by klarstrup** [comment]
There you go! https://github.com/tjek/tjek-js-sdk/releases/tag/release-06.11.2024-10.29

**Comment by jrlarano** [comment]
Cool! Thank you! 🚀

**Pull request merged**
