### PR TITLE
Rejigger IncitoEmbedView to actually POST JSON

### PR DESCRIPTION
**Pull request by mortenbo**

### CODE REVIEW

**Comment by klarstrup** [comment]
With respect to https://github.com/tjek/bumblebee/pull/3865 - can we add a `incitoEmbedLoaded` event here? Signature `incitoEmbedLoaded: [{el: HTMLElement}]`. 

Additionally if this is used to load entire sections, we might want to make sure that section visibility is not tracked for sections that are not loaded yet.

**Review by klarstrup — CHANGES_REQUESTED** [review]
With respect to https://github.com/tjek/bumblebee/pull/3865 - can we add a `incitoEmbedLoaded` event here? Signature `incitoEmbedLoaded: [{el: HTMLElement}]`. 

Additionally if this is used to load entire sections, we might want to make sure that section visibility is not tracked for sections that are not loaded yet.

**Comment by mortenbo** [comment]
@klarstrup Thx for the feedback. How about now?

**Review by klarstrup — APPROVED** [review]
Lookin' good, excited to finally get this superpower. I suspect there will be snags with the real world integrations other than the scroll-to-offer problem, but let's take 'em as they come.

**Pull request merged**
