### PR TITLE
Fix pagedecoration hotspot click event

### PR DESCRIPTION
**Pull request by jrlarano**

### CODE REVIEW

**Review by mortenbo — APPROVED** [review]

**Comment by jrlarano** [comment]
Hi @klarstrup , we need your help in deploying this 🙂

**Comment by klarstrup** [comment]
`shopgun-sdk@4.19.1` is now live on all channels 😁

@mortenbo Maybe it's about time we get @jrlarano set up with the NPM and AWS creds required to publish the SDK?

**Comment by mortenbo** [comment]
@klarstrup What would it require with a similar deploy approach like Squid? Could maybe be powered by GH Actions fully.

**Comment by klarstrup** [comment]
The sdk publish script has a lot more nuance than tagging a commit, multiple packages and versions that change differently requiring multiple inputs. So i don't think that would be possible.
image

**Pull request merged**
