### PR TITLE
Leverage browser lazy loading when possible for massive performance and UX improvements

### PR DESCRIPTION
**Pull request by mortenbo**

### CODE REVIEW

**Review by klarstrup — APPROVED** [review]
very nice and long overdue!

**Comment by mortenbo** [comment]
@klarstrup Thanks. OK to merge?

**Comment by klarstrup** [comment]
Please, go ahead

**Comment by mortenbo** [comment]
@klarstrup Would it be possible to get a staging build of this in Vizsla staging?

**Comment by klarstrup** [comment]
Sure, I will mint a beta SDK build.

**Comment by mortenbo** [comment]
Much appreciated.

**Comment by klarstrup** [comment]
Will be available on staging in ~15 minutes https://console.cloud.google.com/cloud-build/builds/72646c26-8f0e-470b-9871-9e5f54c804fa?project=vizsla-staging

**Pull request merged**
