### PR TITLE
Feat/sidebar menu

### PR DESCRIPTION
**Pull request by jrlarano**
New data options for sidebar:
```
data-component-publication-enable-sidebar="true"
data-component-publication-sidebar-position="left|right(default)"
```

### CODE REVIEW

**Comment by mortenbo** [comment]
Is this supposed to be merged or can it closed? :)

**Comment by jrlarano** [comment]
@mortenbo not yet. I still need to make some adjustments for this. I was just caught up in some other tasks. 😅

**Comment by mortenbo** [comment]
OK, cool. Just wanted to make sure.

**Comment by jrlarano** [comment]
Hi @mortenbo and @klarstrup, this is now ready for your review and testing 🙂

**Comment by mortenbo** [comment]
Cool! Is this only for PDF's or?

Screenshot 2023-02-15 at 07 47 06

And what about mobile?

Screenshot 2023-02-15 at 07 47 35

**Comment by jrlarano** [comment]
@mortenbo this is for both Incito and PDF. Currently, it needs to be reloaded when shifting from desktop to mobile

**Comment by klarstrup** [comment]
> @mortenbo this is for both Incito and PDF. Currently, it needs to be reloaded when shifting from desktop to mobile

Shouldn't be a big deal having it respond properly to screen size changes, see for example `matchMedia` usage for `coarsePointerQuery` in https://github.com/tjek/tjek-js-sdk/blob/develop/lib/verso-browser/verso.ts

**Comment by jrlarano** [comment]
@mortenbo @klarstrup Thanks for giving idea. It's now using `matchMedia` 🙂

**Comment by mortenbo** [comment]
👍 

What to do in these cases?

Screenshot 2023-02-26 at 17 18 58

**Comment by mortenbo** [comment]
I also see this for Davidsen:
Screenshot 2023-02-26 at 17 19 39

**Comment by jrlarano** [comment]
> I also see this for Davidsen

I'll check this out

**Comment by jrlarano** [comment]
@mortenbo I've pushed some changes to fix the issue in Safari where the sidebar is being cut off when the Incito's container has a `position: fixed;` and `overflow: auto;`. Let me know if you still encounter the issue 🙂

**Review by klarstrup — APPROVED** [review]

**Comment by mortenbo** [comment]
Looks good. Only thing is that the UX is weird in mobile because I think I close the sidebar by clicking on the button that closes the catalog.

**Review by mortenbo — APPROVED** [review]

**Pull request merged**
