### PR TITLE
[Template] Fix Paged viewer overflow

### PR DESCRIPTION
**Pull request by jrlarano**

### CODE REVIEW

**Review by klarstrup — CHANGES_REQUESTED** [review]
Can we accomplish this without messing with CSS outside of our component? :/

**Review by klarstrup — CHANGES_REQUESTED** [review]
This still applies global styling to a website that is not ours, that's gonna bite us in the hind eventually

**Comment by mortenbo** [comment]
@klarstrup Isn't this the only way to disable scroll on the site?

**Comment by klarstrup** [comment]
> @klarstrup Isn't this the only way to disable scroll on the site?

if the goal is to disable scrolling, we should capture scroll inputs on our component and block them as appropriate

**Comment by jrlarano** [comment]
> > @klarstrup Isn't this the only way to disable scroll on the site?
> 
> if the goal is to disable scrolling, we should capture scroll inputs on our component and block them as appropriate

The goal is not only the for the scroll inputs but to also hide the scrollbar when publication viewer is open. Is there any other way apart from this?

**Comment by klarstrup** [comment]
> > > @klarstrup Isn't this the only way to disable scroll on the site?
> > 
> > 
> > if the goal is to disable scrolling, we should capture scroll inputs on our component and block them as appropriate
> 
> The goal is not only the for the scroll inputs but to also hide the scrollbar when publication viewer is open. Is there any other way apart from this?

yeah stay within 100vh, you can also use position: fixed; to position the container edge-to-edge in the viewport

**Pull request merged**
