### PR TITLE
Allow inserting Incito into a nested scroll element

### PR DESCRIPTION
**Pull request by mortenbo**
I need to insert Incito into a scrollable div where the html tag has overflow: hidden. This PR allows this.

### CODE REVIEW

**Review by martensievers — APPROVED** [review]
I'm not very familiar with the SDK but to me it looks fine.

**Comment by mortenbo** [comment]
@klarstrup Any feedback?

**Review by klarstrup — CHANGES_REQUESTED** [review]
Oh, sorry for neglecting this.

I think instead of an option we should aim to "just work" and find the nearest scroll container, something like.

```ts
function getClosestScrollable(el: HTMLElement) {
  const hasScrollableContent = el.scrollHeight > el.clientHeight;
  const isOverflowHidden = window.getComputedStyle(el).overflowY === "hidden";
  if (hasScrollableContent && !isOverflowHidden) return el;

  if (!el.parentElement) return null;

  return getClosestScrollable(el.parentElement);
}
```

Is the move away from the native HTML `loading="lazy"` related to this change?

**Comment by mortenbo** [comment]
We can do that too. The reason for this PR is because if you place Incito inside a div that takes care of overflow instead of body, loading=lazy doesn't work properly. Normally, loading=lazy means it *lazy* loads ahead of time but in this case, it only loads the images once they enter the viewport (vs. ahead of time).

I really don't want to stop using loading=lazy but this was the best alternative solution.

**Comment by klarstrup** [comment]
Gotcha!

**Comment by mortenbo** [comment]
I won't be needing this after all so closing this. Thanks for giving it a looksie though!

**Pull request closed without merging**
