### PR TITLE
New offer modal and shopping list

### PR DESCRIPTION
**Pull request by jrlarano**

### CODE REVIEW

**Comment by jrlarano** [comment]
@klarstrup can we build a test link for this?

**Comment by klarstrup** [comment]
Yeah sorry give me a second I haven't done this procedure on my new work pc yet

**Comment by klarstrup** [comment]
Published current version as https://unpkg.com/browse/shopgun-sdk@0.0.0-experimental-30c8aa9-20240702/

**Comment by jrlarano** [comment]
@klarstrup Cool! Thank you so much! 😄

**Review by mortenbo — APPROVED** [review]
Cool. Make sure we properly test this with multiple people on multiple screens/devices before going to prod.

**Review by klarstrup — APPROVED** [review]

**Pull request merged**
