### PR TITLE
[Spans] Add markdown support

### PR DESCRIPTION
**Pull request by jrlarano**
Relates to: https://github.com/tjek/bumblebee/pull/4199, https://github.com/tjek/octopus/issues/305

### CODE REVIEW

**Comment by jrlarano** [comment]
Hi @mortenbo this PR is also required for the markdown support 🙂

**Comment by mortenbo** [comment]
@jrlarano Do we need the <span/> and data-name?

**Comment by jrlarano** [comment]
@mortenbo No, we don't need that anymore. I just missed to remove that one. It's removed now 🙂

**Review by klarstrup — CHANGES_REQUESTED** [review]
You need to write the styles directly on the element instead of wrapping with styling elements. `<strong>` and `<em>` aren't reliably styled the same across browsers

**Review by klarstrup — APPROVED** [review]

**Pull request merged**
